# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b2bb564a16815af84a0e0b3a0684150c5b27a1d4a7d87bbe6f81ac91a7bcec8487c2903ed881e3aaab63dbd705d72c4ae98c6a182eb1a164e4412bdf26f67b9

test:
  secret_key_base: 324e24d4889bf1ac7bd626874abcbe358778f8cd0d72a6cdd619d3d88bf7764b9a4c9d61e7dce34ca2574453a03f308677b6f5a8fc8e71740dd6dd1574e2e15e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
